### ISSUE TITLE
Bot says it has an open game, but it doesn't 

### ISSUE THREAD

**Issue by jsfernandes1** [AmanoTeam/UnuRobot#18]
The bot often says that there is an open match and so people cannot start or join the match. Even a group administrator cannot use the /kill@UnuRobot command to close the already open game in this situation, for being told that you are not allowed to do so (even if you clicked the button to participate, the supposed game is already open and has not started).
![Screenshot_20241106_223055_AyuGram](https://github.com/user-attachments/assets/b44dec20-7c1e-439f-bc32-8da3ae3efbf0)

**Comment by RianFC** [comment]
you are the group administrator, if not ask the administrator to run the /kill command

**Comment by AndrielFR** [comment]
Try `/leave` or `/close`

**Comment by jsfernandes1** [comment]
I am an administrator of the group, yet the /kill, /leave or /close commands did not work. Even removing and adding the bot back to the group didn't solve the problem. It stays like this until the bot starts working again whenever it wants.

**Comment by RianFC** [comment]
try again

**Comment by Sunda001** [comment]
@RianFC nice
