### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [AmanoTeam/UnuRobot#5]
https://hosted.weblate.org/projects/unurobot/#information says AGPLv3-only, but according to
https://github.com/AmanoTeam/UnuRobot/blob/master/locales/__init__.py
https://github.com/AmanoTeam/UnuRobot/blob/master/database.py and so on are "or later".

The translation license can be changed to "AGPLv3-or-later" in
https://hosted.weblate.org/settings/unurobot/bot/  and
https://hosted.weblate.org/settings/unurobot/glossary/

**Comment by alissonlauffer** [comment]
Hello, thanks for reporting.
I did set up Weblate in a rush, so I didn't take care of the right license. But it should be AGPLv3-or-later now. Thanks!

**Comment by comradekingu** [comment]
@alissonlauffer The license changed, but now the project isn't there.
https://hosted.weblate.org/project/unurobot/

**Comment by alissonlauffer** [comment]
Shouldn't the URL be https://hosted.weblate.org/projects/unurobot/?

**Comment by comradekingu** [comment]
@alissonlauffer Aha. All is well. I will start translating it later on :)
